version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    

  rmq:
    image: rabbitmq:3.8.3-alpine
    container_name: rmq
    

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 50 && python3 orchestrator.py"
    volumes:
      - .:/project-test/kiks
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - rmq
    depends_on:
      - zoo
      - rmq
    restart: on-failure
    ports:
      - 80:5000
    container_name: orchestrator
    

  sync:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 45 && python sync_slave_worker.py"
    volumes:
      - .:/project-test/kiks
    links:
      - rmq
      - zoo
      - sync-mongo
    depends_on:
      - rmq
      - zoo
      - sync-mongo
    restart: on-failure
    

  sync-mongo:
    image: mongo:latest
    restart: always
    container_name: sync-mongo
    environment:
      - TEAM_NAME=CC_0230_0688_1002_1799
  
  workers:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - .:/project-test/kiks
    links:
      - rmq
      - zoo
    depends_on:
      - rmq
      - zoo
    image: workers:latest
    restart: on-failure
    
  

     
