version: '3.1'

services:
  zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  rmq:
    image: rabbitmq:3.8.3-alpine

  master:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && python master.py"
    volumes:
      - .:/project-test/richa
    links:
      - rmq
      - zoo
      - master-mongo
    depends_on:
      - rmq
      - zoo
      - master-mongo
    restart: on-failure
    


  slave1:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 35 && python slave.py"
    volumes:
      - .:/project-test/richa
    links:
      - rmq
      - zoo
      - slave-mongo1
    depends_on:
      - rmq
      - zoo
      - slave-mongo1
    restart: on-failure

  slave2:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 35 && python slave1.py"
    volumes:
      - .:/project-test/richa
    links:
      - rmq
      - zoo
      - slave-mongo2
    depends_on:
      - rmq
      - zoo
      - slave-mongo2
    restart: on-failure
   

  orchestrator:
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "sleep 35 && python3 orchestrator.py"
    volumes:
      - .:/project-test/richa
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - rmq
    depends_on:
      - zoo
      - rmq
    restart: on-failure  
    ports: 
      - 80:5000
    

  master-mongo:
    image: mongo:latest
    restart: always
    container_name: master-mongo
    environment:
      - TEAM_NAME=CC_0230_0688_1002_1799

  slave-mongo1:
    image: mongo:latest
    restart: always
    container_name: slave-mongo1
    environment:
      - TEAM_NAME=CC_0230_0688_1002_1799

  slave-mongo2:
    image: mongo:latest
    restart: always
    container_name: slave-mongo2
    environment:
      - TEAM_NAME=CC_0230_0688_1002_1799
   
